scss_files: "src/**/*.scss"
exclude: 'src/theme/Palette.scss'
linters:
  PropertySortOrder:
    order: smacss

  SelectorFormat:
    convention: camel_case

  NameFormat:
#    convention: camel_case
    enabled: false

  Indentation:
    width: 4

  SelectorDepth:
    enabled: false

  NestingDepth:
    enabled: false

  UnnecessaryParentReference:
    enabled: false